kartographerz_cartography:
    resource: "@KartographerzCartographyBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/cartography
    requirements:
        _locale: en|fr

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
fos_user:
    resource: "@KartographerzUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /{_locale}/admin/group
    requirements:
        _locale: en|fr
    
_login:
    pattern: /{_locale}/login
    requirements:
        _locale: en|fr
        

        
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/administration

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/administration

