kartographerz_cartography:
    resource: "@KartographerzCartographyBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/cartography
    requirements:
        _locale: en|fr

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
fos_user:
    resource: "@KartographerzUserBundle/Resources/config/routing/all.xml"