kartographerz_cartography_index:
    path:     /
    defaults: { _controller: KartographerzCartographyBundle:Cartography:index }

kartographerz_cartography_view:
    path:     /view/{id}
    defaults: { _controller: KartographerzCartographyBundle:Cartography:view }
    requirements:
        id : ^[1-9]\d*

kartographerz_cartography_add:
    path:     /add
    defaults: { _controller: KartographerzCartographyBundle:Cartography:add }
    
kartographerz_cartography_addElement:
    path:     /addElement
    defaults: { _controller: KartographerzCartographyBundle:Element:add }
    
kartographerz_cartography_addElementType:
    path:     /addElementType
    defaults: { _controller: KartographerzCartographyBundle:Element:addElementType }


kartographerz_cartography_cartographyList:
    path: /cartographyList
    defaults: { _controller: KartographerzCartographyBundle:Cartography:list }
    
kartographerz_element_elementList:
    path: /elementList
    defaults: { _controller: KartographerzCartographyBundle:Element:list }