kartographerz_cartography_index:
    path:     /
    defaults: { _controller: KartographerzCartographyBundle:Cartography:index }

kartographerz_cartography_view:
    path:     /view/{id}
    defaults: { _controller: KartographerzCartographyBundle:Cartography:view }

kartographerz_cartography_add:
    path:     /add
    defaults: { _controller: KartographerzCartographyBundle:Cartography:add }
